### ISSUE TITLE
Unable to generate tilesets

### ISSUE THREAD

**Issue by soastao** [diasurgical/modding-tools#7]
I'm unable to get the tools used to generate the tilesets in PNG format,I am very distressed，
please mail to soastao@163.com，thank you so much

**Comment by mewmew** [comment]
Hi @soastao,

You seem to be in the same boat as @Jmgr, who reported a similar issue at the beginning of this month. Please refer to #6, hope it should help provide relief.

Closing this issue as a duplicate for now. Feel free to comment in #6.

Cheers,
Robin

**Edit:** @AJenbo or @qndel, care to close this issue as a duplicate? I don't have permissions :)

**Comment by AJenbo** [comment]
@mewmew you now have a new invite
